# As the name suggests this script loads all the file level bug prediction metric 
# generated by git blame and python scripts and prepare an unified metric

setwd('/home/bairay/bitbucket/szz/R')
loadData<-function() {
  
  ownership_metric = read.csv('/biodata/ec_data/result/process_metric/ownership_metric.csv')
  ownership        = read.csv('/biodata/ec_data/result/process_metric/ownership.csv')
  change_scatter   = read.csv('/biodata/ec_data/result/process_metric/change_scatter.csv')
  neighbour        = read.csv('/biodata/ec_data/result/process_metric/neighbour.csv')

  everything_snap_exp = read.csv('/biodata/ec_data/result/process_metric/log_based_data/everything_snap_exp.csv')
  file_stat = read.csv('/biodata/ec_data/result/process_metric/log_based_data/log_file_metric.csv')
  file_exp  = read.csv('/biodata/ec_data/result/process_metric/log_based_data/file_exp.csv')

  ddev = sqldf('select proj_name, snap_name, src_file, 
              count(distinct author) ddev
             from ownership 
             group by proj_name, snap_name, src_file')


  max_contribution = sqldf('select proj_name, snap_name, src_file, author, 
                          max(contribution) max_contribution,
                          pcent_contribution as oexp,
                          loc
                          from ownership 
                          group by proj_name, snap_name, src_file'
                        )
  ow_ch = merge(ownership_metric,change_scatter)

  colnames(ow_ch)[which(names(ow_ch) == "highest_pcent_contribution")] <- "own"
  colnames(ow_ch)[which(names(ow_ch) == "lowest_contributors")] <- "minor"
  colnames(ow_ch)[which(names(ow_ch) == "ch_scatter")] <- "sctr"
  
  temp_total <- sqldf('select proj_name, snap_name, sum(added_line_num) as total_add, 
                      sum(deleted_line_num) as total_del
                      from ow_ch
                      group by proj_name,snap_name'
                      )
  ow_ch = merge(ow_ch, temp_total)
  ow_ch$add = ow_ch$added_line_num / ow_ch$total_add
  ow_ch$del = ow_ch$deleted_line_num / ow_ch$total_del
  final = merge(ow_ch, ddev)
  final = final[,c("proj_name","prev_snap","snap_name","src_file",
                   "own","minor","sctr",
                   "add","del","ddev")]
  
  file_stat_exp = merge(file_stat,file_exp)
  file_stat_exp = file_stat_exp[,c("language","project","prev_snaps","next_snaps","file_name",
                                   "commit_count","adev","exp")]
  
  colnames(file_stat_exp)[which(names(file_stat_exp) == "project")] <- "proj_name"
  colnames(file_stat_exp)[which(names(file_stat_exp) == "next_snaps")] <- "snap_name"
  colnames(file_stat_exp)[which(names(file_stat_exp) == "prev_snaps")] <- "prev_snap"
  colnames(file_stat_exp)[which(names(file_stat_exp) == "file_name")] <- "src_file"
  
  temp_final = merge(final, file_stat_exp, all.x=TRUE)
   
  temp_final$language[is.na(temp_final$language)] <- 'java'
  temp_final[is.na(temp_final)] <- 0
  
  mx = max_contribution[,c("proj_name","snap_name","src_file","oexp")]
  final = merge(temp_final,mx)
  colnames(neighbour)<-c("proj_name","prev_snap","snap_name","src_file","nadd","ndel","nsctr")
  final = merge(final,neighbour,all.x=TRUE)
  final[is.na(final)] <- 0
  
  return(final)
}

get_bug <- function(project){
  buggy_file   = paste('/biodata/ec_data/corpus/',project,'/ss_bugdata.csv',sep="")
  bf   = read.csv(buggy_file)
  return(bf)
}

loadBugData<-function() {

  atm = get_bug('atmosphere')
  db = get_bug('derby')
  el = get_bug('elasticsearch')
  fb = get_bug('facebook-android-sdk')
  lu = get_bug('lucene')
  nt = get_bug('netty')
  oj = get_bug('openjpa')
  ps = get_bug('presto')
  qp = get_bug('qpid')
  wkt = get_bug('wicket')
  all_bugs = rbind(atm,db,el,fb,lu,nt,oj,ps,qp,wkt)
  
  bug_per_file = sqldf('select project, snapshot, ss_file_name, sum(is_bug) as bug
                       from all_bugs
                       group by project, snapshot, ss_file_name')
  
  colnames(bug_per_file) = c("proj_name","snap_name","src_file","bug")
  final = loadData()
  final_bug = merge(final,bug_per_file,all.x=TRUE)
  final_bug[is.na(final_bug)] <- 0
  
  return(final_bug)
}

run<-function() {
  final_bug = loadBugData()
  temp = final_bug
  fb = sqldf('select final_bug.*, temp.bug as prev_bug from final_bug 
             left join temp on
             final_bug.proj_name = temp.proj_name and
             final_bug.prev_snap    = temp.snap_name  and 
             final_bug.src_file  = temp.src_file')
  fb[is.na(fb)] <- 0
  write.csv(fb,'data/final_file_metric.csv',row.names=FALSE)
}