# This script merges a line's entropy with bug information
# The bug information is generated by SZZ
# The entropies are generated at each snapshot

setwd('/home/bairay/bitbucket/szz/R')
get_bug <- function(project){
  buggy_file   = paste('/biodata/ec_data/corpus/',project,'/ss_bugdata.csv',sep="")
  bf   = read.csv(buggy_file)
  return(bf)
}

merge_entropy_bug <- function(project, all_commits){
  
  entropy_file = paste('/biodata/ec_data/snapshots/',project,'/entropy.csv',sep="")
  buggy_file   = paste('/biodata/ec_data/corpus/',project,'/ss_bugdata.csv',sep="")
  
  evr = all_commits[all_commits$project==project,]
  entr = read.csv(entropy_file)
  bf   = read.csv(buggy_file)
  
  mb = merge(bf,evr,by.x="bi_sha",by.y="sha")
  mb2 = merge(mb,evr,by.x="bf_sha",by.y="sha")
  
  mb2$bf_date = as.Date(mb2$author_date.y)
  mb2$bi_date = as.Date(mb2$author_date.x)
  mb2$duration = as.numeric(mb2$bf_date - mb2$bi_date)
  
  
  bf = mb2[,c("project.x","snapshot","ss_file_name","ss_line_num","is_bug","duration")]
  colnames(bf) <- c("project","snapshot","filename","source_line","is_bug","bug_duration")
  ubf = unique(bf)
  #colnames(ubf)[colnames(ubf)=="ss_file_name"] <- "filename"
  #colnames(ubf)[colnames(ubf)=="ss_line_num"] <- "source_line"
  
  entr$entropy = (entr$prefix + entr$suffix)/2
  
  eb = merge(entr,ubf,all.x=TRUE)
  
  eb = eb[,c("project","snapshot","filename","source_line","token_line","entropy","is_bug","bug_duration")]
  eb$is_bug[is.na(eb$is_bug)] <- 0
  
  #filter out 1st line of token as they are often blank lines
  eb = eb[eb$token_line!=1,]
  
  #filter out the lines that we were not able to map successfully from token to source
  eb = eb[eb$token_line!=-1,]
   
  return(eb)
}



run<-function() {
  
  everything = read.csv('/biodata/ec_data/result/process_metric/log_based_data/err_corr_july_2015.everything.csv')
  everything = everything[,c("project","sha","author_date")]
  everything = unique(everything)
  atm = merge_entropy_bug('atmosphere',everything)
  db = merge_entropy_bug('derby',everything)
  el = merge_entropy_bug('elasticsearch',everything)
  fb = merge_entropy_bug('facebook-android-sdk',everything)
  lu = merge_entropy_bug('lucene',everything)
  nt = merge_entropy_bug('netty',everything)
  oj = merge_entropy_bug('openjpa',everything)
  ps = merge_entropy_bug('presto',everything)
  qp = merge_entropy_bug('qpid',everything)
  wkt = merge_entropy_bug('wicket',everything)
  all = rbind(atm,db,el,fb,lu,nt,oj,ps,qp,wkt)
  
  write.csv(all,'data/entropy.csv',row.names=FALSE)
  return(all)
}


#some further analysis to check difference of 
#line entropy between buggy and non-buggy lines

t_test<-function(data, threshold) {
  buggy = data[data$is_bug==1,]
  buggy = buggy[buggy$bug_duration <= threshold,]
  nbuggy = data[data$is_bug==0,]
  t = t.test(buggy$entropy,nbuggy$entropy)
  c = cohensD(buggy$entropy,nbuggy$entropy)
  return(list(t=t,c=c,n=nrow(buggy)))
  
}

print_t_test<-function(data) {
  buggy = data[data$is_bug == 1,]
  total_bugs = nrow(buggy)
  min_d = min(buggy$bug_duration)
  max_d = max(buggy$bug_duration)
  
  #df = data.frame()
  df <- data.frame(threshold=integer(),
                   num_bug=integer(),
                   total_bugs=integer(),
                   conf_int0=double(),
                   conf_int1=double(),
                   mean_buggy_entr = double(),
                   mean_nbuggy_entr = double(),
                   p_value = double(),
                   cohend = double(),
                   stringsAsFactors=FALSE
                   )
    
    
  
  for (i in seq(30, max_d, 30)) {
  #for (i in c(min_d+30, 60, 90, 120, 150, 180, 210, 240, 270, 300, 330, 360, 
  #            720, 1080, max_d)) {
    
    t = t_test(data,i)
    tTestResult = sapply(t$t,unlist)
    cohendDResult = sapply(t$c,unlist)
    
    conf_int = tTestResult$conf.int
    
    writeLines(paste(i,",",
                     round(t$n/total_bugs,2), ",",
                     round(tTestResult$conf.int[1],2),",",
                     round(tTestResult$conf.int[2],2),",",
                     round(tTestResult$estimate[[1]],2),",",
                     round(tTestResult$estimate[[2]],2),",",
                     tTestResult$p.value,",",
                     round(cohendDResult,3)
                     ))
    
  df1 = data.frame(i,t$n,total_bugs,
                 tTestResult$conf.int[1],
                 tTestResult$conf.int[2],
                 tTestResult$estimate[[1]],
                 tTestResult$estimate[[2]],
                 tTestResult$p.value,
                 cohendDResult)
    df = rbind(df,df1)
  } 
  
  colnames(df) = c("theshold","num_bug","total_bugs",
                   "conf_int0","conf_int1",
                   "mean_buggy_entr","mean_nbuggy_entr",
                   "p_value","cohend")
  
  return(df)
  
}

#p <- ggplot(df1, aes(x=th, y=conf_int0))
#p + geom_line()
#p + scale_x_continuous(breaks=c(3,6,9,12,24,36,48,60,120),"bug duration (months)") +   scale_y_continuous("entropy differece (bug > nonbug)")